name: Deploy CRM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |

            echo "===================================="
            echo "Starting CRM Deployment..."
            echo "===================================="

            cd /var/www/crm/Majisa-Whatsapp-CRM

            git pull origin main

            echo "Installing Server Dependencies..."

            cd server
            npm install

            echo "Installing Client Dependencies..."

            cd ../client
            npm install

            echo "Building React..."

            npm run build

            echo "Updating Frontend..."

            rm -rf /var/www/crm-frontend/*
            cp -r dist/* /var/www/crm-frontend/

            echo "Restarting PM2..."

            cd ../server
            pm2 restart majisa-crm

            echo "Saving PM2..."

            pm2 save

            echo "Deployment Completed Successfully"